# Generated by Django 3.0.7 on 2020-06-12 15:04

from django.db import migrations
import isc_common.fields.code_field


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20200122_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='jasper_reports_users',
            name='editor_identifier',
            field=isc_common.fields.code_field.CodeField(blank=True, null=True),
        ),
    ]
