#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['briar_repl']

package_data = \
{'': ['*']}

install_requires = \
['colorful>=0.5.4',
 'prompt-toolkit>=3.0.14',
 'httpx>=0.16.1',
 'websockets>=8.1.0',
 'psutil>=5.8.0']

setup(name='briar_repl',
      version='21.2.20',
      description='briar cli-messenger for briar:headless',
      author='fphemeral',
      author_email='fphemeral@i2pmail.org',
      url='https://code.briarproject.org/fphemeral/briar_repl',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.7',
     )
