# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-30 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_auto_20181220_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread', to='alerts.Message'),
        ),
    ]
