
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-16T17:49:24+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "5d9ab04b7853f0854d1e5b7ffe5299c3c7c3b466",
 "version": "1.0.3rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
