# Generated by Django 3.0.3 on 2020-02-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isc_common', '0047_remove_progresses_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresses',
            name='message',
            field=models.TextField(default=None),
        ),
        migrations.DeleteModel(
            name='AuditModelEx',
        ),
    ]
