
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-16T14:54:00-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "d2ff4906b4a82591cff7c808c039d0e63a17fb7f",
 "version": "v0.1.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
