
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-15T23:26:03+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0fe5012e6c658fe570a38d3de11e4f8ef04f7956",
 "version": "0.8.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
