# coding: utf-8

"""
    FreeClimb API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import freeclimb
from freeclimb.models.update_conference_participant_request import UpdateConferenceParticipantRequest  # noqa: E501
from freeclimb.rest import ApiException


class TestUpdateConferenceParticipantRequest(unittest.TestCase):
    """UpdateConferenceParticipantRequest unit test stubs"""

    def setUp(self):
        self.update_conference_participant_request = UpdateConferenceParticipantRequest()

    def tearDown(self):
        pass

    def testUpdateConferenceParticipantRequest(self):
        """Test UpdateConferenceParticipantRequest"""
        # construct object with mandatory attributes with example values
        # model = freeclimb.models.update_conference_participant_request.UpdateConferenceParticipantRequest()  # noqa: E501
        self.assertTrue(isinstance(self.update_conference_participant_request, UpdateConferenceParticipantRequest))


if __name__ == '__main__':
    unittest.main()
