# Generated by Django 3.1.3 on 2020-12-07 14:43

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('instagram', wagtail.core.fields.StreamField([('instagram', wagtail.core.blocks.StructBlock([('instagram', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('embed', wagtail.embeds.blocks.EmbedBlock())])))]))], blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Gallery Page',
                'verbose_name_plural': 'Gallery Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
