# Generated by Django 2.1.7 on 2019-02-16 20:53

import django.utils.timezone
import isc_common.fields.related
from django.conf import settings
from django.db import migrations, models
from isc_common.fields.code_field import JSONFieldIVC


class Migration(migrations.Migration):

    dependencies = [
        ('isc_common', '0003_auto_20190216_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Permission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('id_old', models.BigIntegerField(blank=True, null=True, verbose_name='Идентификатор старый')),
                ('deleted', models.BooleanField(db_index=True, default=False, verbose_name='Признак удаления')),
                ('editing', models.BooleanField(default=True, verbose_name='Возможность редактирования')),
                ('deliting', models.BooleanField(default=True, verbose_name='Возможность удаления')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Последнее обновление')),
                ('permission', JSONFieldIVC()),
                ('user', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('widget', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='isc_common.Widgets_trees')),
            ],
            options={
                'verbose_name': 'Доступы для пользователей',
            },
        ),
    ]
