# Generated by Django 3.0.3 on 2020-02-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isc_common', '0037_progresses_label_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresses',
            name='label_contents',
            field=models.TextField(),
        ),
    ]
