# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topic.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import trace_pb2 as trace__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='topic.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0btopic.proto\x1a\x0btrace.proto\"e\n\x0cTopicMessage\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\x12\x15\n\x05trace\x18\x04 \x01(\x0b\x32\x06.Trace\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c*O\n\x0c\x44\x61taLocation\x12\x07\n\x03\x43PU\x10\x00\x12\x07\n\x03GPU\x10\x01\x12\x0f\n\x0b\x43PU_NDARRAY\x10\x02\x12\x0f\n\x0bGPU_NDARRAY\x10\x03\x12\x0b\n\x07MESSAGE\x10\x04\x62\x06proto3'
  ,
  dependencies=[trace__pb2.DESCRIPTOR,])

_DATALOCATION = _descriptor.EnumDescriptor(
  name='DataLocation',
  full_name='DataLocation',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CPU', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GPU', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CPU_NDARRAY', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GPU_NDARRAY', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MESSAGE', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=131,
  serialized_end=210,
)
_sym_db.RegisterEnumDescriptor(_DATALOCATION)

DataLocation = enum_type_wrapper.EnumTypeWrapper(_DATALOCATION)
CPU = 0
GPU = 1
CPU_NDARRAY = 2
GPU_NDARRAY = 3
MESSAGE = 4



_TOPICMESSAGE = _descriptor.Descriptor(
  name='TopicMessage',
  full_name='TopicMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='TopicMessage.topic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source', full_name='TopicMessage.source', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='TopicMessage.timestamp', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trace', full_name='TopicMessage.trace', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='TopicMessage.data', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=129,
)

_TOPICMESSAGE.fields_by_name['trace'].message_type = trace__pb2._TRACE
DESCRIPTOR.message_types_by_name['TopicMessage'] = _TOPICMESSAGE
DESCRIPTOR.enum_types_by_name['DataLocation'] = _DATALOCATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TopicMessage = _reflection.GeneratedProtocolMessageType('TopicMessage', (_message.Message,), {
  'DESCRIPTOR' : _TOPICMESSAGE,
  '__module__' : 'topic_pb2'
  # @@protoc_insertion_point(class_scope:TopicMessage)
  })
_sym_db.RegisterMessage(TopicMessage)


# @@protoc_insertion_point(module_scope)
