# Generated by Django 3.0 on 2020-04-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appel_crises', '0004_auto_20200420_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signature',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='verified',
        ),
        migrations.AddField(
            model_name='signature',
            name='email_sent_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='signature',
            name='verified_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
