# Generated by Django 3.0.5 on 2020-04-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appel_crises', '0010_auto_20200430_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calloutemail',
            name='circonscription_number',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
