# Generated by Django 3.0.5 on 2020-05-05 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appel_crises', '0017_signature_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='added_to_newsletter_list',
            field=models.BooleanField(default=False),
        ),
    ]
