# Generated by Django 3.0.5 on 2020-05-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appel_crises', '0020_blacklistedemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calloutemail',
            name='circonscription_numbers',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
