
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-17T21:18:52+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d835f4f5ab754ce11d6255e1cdcc2eaec07fcc9a",
 "version": "1.12"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
