# Generated by Django 2.0.1 on 2021-01-23 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sso_server.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.TextField(db_index=True, unique=True, verbose_name='Access token')),
                ('refresh', models.TextField(default=sso_server.utils.generate_random, verbose_name='Refresh token')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время создания')),
                ('valid_until', models.DateTimeField(default=sso_server.utils.time_slice, verbose_name='Срок годности до')),
                ('revoked', models.BooleanField(default=False, verbose_name='Отозван')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Access/Refresh Token',
                'verbose_name_plural': 'Access/Refresh Tokens',
            },
        ),
    ]
