# Generated by Django 2.2.4 on 2019-08-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clndr', '0043_auto_20190823_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift_day',
            name='numdayinweek',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
