# Generated by Django 2.2.4 on 2019-08-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clndr', '0055_auto_20190825_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shifts',
            name='order',
        ),
        migrations.AddField(
            model_name='calendar_shifts_days',
            name='shiftorder',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
