# This file was generated by mettle.genes.db.GenPy3 [ver 2.1] on Mon Feb 15 23:21:02 2021
#

import copy
import datetime
import uuid
import time
import mettle.lib
import mettle.io
import mettle.db

class oCorrTypeAllowRegexForType(mettle.io.ISerializable):

    def __init__(self,
                 allow_id: str = '',
                 regex: str = ''):
        """
        Constructor.

        :param allow_id: str
        :param regex: str
        """
        self.allow_id = allow_id
        self.regex = regex

    def clear(self):
        """
        Clears all member variables for this database record.
        """
        self.allow_id = ''
        self.regex = ''

    def _name(self) -> str:
        """
        Name of the record.

        :return: The name.
        """
        return 'oCorrTypeAllowRegexForType'

    def _serialize(self, _w: mettle.io.IWriter, _oname: str = None):
        """
        Serialize record to a stream.

        :param _w:
        :param _oname:
        """
        if _oname == None:
            _oname = self._name()

        _w.write_start(_oname)
        _w.write_string("allow_id", self.allow_id)
        _w.write_string("regex", self.regex)
        _w.write_end(_oname)

    def _deserialize(self, _r: mettle.io.IReader, _oname: str = None):
        """
        Deserialize record from a stream.

        :param _r:
        :param _oname:
        """
        if _oname == None:
            _oname = self._name()

        _r.read_start(_oname)
        self.allow_id = _r.read_string("allow_id")
        self.regex = _r.read_string("regex")
        _r.read_end(_oname)

    def _copy_from(self, rec: "oCorrTypeAllowRegexForType"):
        """
        Copies the column from the rec into this record.

        :param rec: The source record.
        """
        self.allow_id = rec.allow_id
        self.regex = rec.regex

    def __repr__(self) -> str:
        return '<CorrTypeAllow [allow_id:%.32s, regex:%.32s]>' % (
            self.allow_id, self.regex)


    class List(list, mettle.io.ISerializable):
        """
        List Class
        """

        def _name(self) -> str:
            """
            Name of the list.

            :return: The name
            """
            return 'oCorrTypeAllowRegexForType.List'

        def _serialize(self, _w: mettle.io.IWriter, _oname: str = None):
            """
            Serialize the list to a stream.

            :param _w:
            :param _oname:
            """
            if _oname == None:
                _oname = self._name()

            _w.write_start_list(_oname, len(self))

            for _rec in self:
                _rec._serialize(_w)

            _w.write_end(_oname)

        def _deserialize(self, _r: mettle.io.IReader, _oname: str = None):
            """
            Deserialize the list from a stream.

            :param _r:
            :param _oname:
            """
            if _oname == None:
                _oname = self._name()

            _cnt = _r.read_start_list(_oname)

            while _cnt >= 1:
                _rec  = oCorrTypeAllowRegexForType()
                _cnt -= 1
                _rec._deserialize(_r)
                self.append(_rec)

            _r.read_end(_oname)

        def __repr__(self) -> str:
            return '<oCorrTypeAllowRegexForType.List[%d]>' % (len(self))

