# coding: utf-8

"""
    FreeClimb API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import freeclimb
from freeclimb.percl.send_digits import SendDigits  # noqa: E501
from freeclimb.rest import ApiException


class TestSendDigits(unittest.TestCase):
    """SendDigits unit test stubs"""
    digits='1234#'

    def setUp(self):
        self.send_digits = SendDigits(digits=self.digits)

    def tearDown(self):
        pass

    def testSendDigits(self):
        """Test SendDigits"""
        # construct object with mandatory attributes with example values
        # percl = freeclimb.percl.SendDigits()  # noqa: E501
        self.assertTrue(isinstance(self.send_digits, SendDigits))
        self.assertEqual(self.digits, self.send_digits.get('SendDigits').get('digits'))
        self.assertTrue(hasattr(self.send_digits, 'pause_ms'))

if __name__ == '__main__':
    unittest.main()
