# Generated by Django 2.2.4 on 2019-08-22 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twits', '0002_auto_20190819_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_permission',
            name='id_old',
        ),
        migrations.RemoveField(
            model_name='chat_user_permission',
            name='id_old',
        ),
        migrations.RemoveField(
            model_name='chat_users',
            name='id_old',
        ),
        migrations.RemoveField(
            model_name='chats',
            name='id_old',
        ),
    ]
