# Generated by Django 2.2.5 on 2019-09-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twits', '0006_auto_20190905_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_user_user',
            name='common_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
