# This file is generated by setup.py. DO NOT EDIT!

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

version = '0.2.1'
git_version = '20dfff103b5585803dcb3b60d6714479b6161613'
