
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-16T11:27:57-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "617d8838234d44bf09a733c67e935cdc804d87fa",
 "version": "v0.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
