#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright (C) 2017-2020  The SymbiFlow Authors.
#
# Use of this source code is governed by a ISC-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/ISC
#
# SPDX-License-Identifier: ISC

# ** WARNING **
# This file is auto-generated by the update_version.py script.
# ** WARNING **

version_str = "0.0.2.post61"
version_tuple = (0, 0, 2, 61)
try:
    from packaging.version import Version as V
    pversion = V("0.0.2.post61")
except ImportError:
    pass

git_hash = "6308864592c6aacd5b87de5486b498a6ddde72b1"
git_describe = "v0.0.2-61-g6308864"
git_msg = """\
commit 6308864592c6aacd5b87de5486b498a6ddde72b1
Merge: 4e86c22 6f720ee
Author: Tim Ansell <me@mith.ro>
Date:   Thu Feb 18 17:01:14 2021 -0800

    Merge pull request #59 from mithro/pypi-small-fixes

    Publish to PyPi

"""
