
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-20T22:01:45-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "dfa15dbd46fe017963e8d8d7b39c29f770a41902",
 "version": "1.8.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
