
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-20T22:36:31+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6858c7ee82d957754ae5cd4e402d5ba391103bb2",
 "version": "v0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
