
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-22T13:17:20-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "5ccbe4a1c4d4c3ecf89bcb73b56007164089ba44",
 "version": "4.4.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
