import enum

class Language(enum.Enum):
    CHINESE_TW = "zh-TW"
    CHINESE_HK = "zh-HK"
    CHINESE_CN = "zh-CN"
    SWEDISH = "sv-SE"
    RUSSIAN = "ru-RU"
    PORTUGUESE_PT = "pt-PT"
    PORTUGUESE_BR = "pt-BR"
    POLISH = "pl-PL"
    DUTCH = "nl-NL"
    NORWEGIAN = "nb-NO"
    KOREAN = "ko-KR"
    JAPANESE = "ja-JP"
    ITALIAN = "it-IT"
    FRENCH_CA = "fr-CA"
    FRENCH_FR = "fr-FR"
    FINNISH = "fi-FI"
    SPANISH_MX = "es-MX"
    SPANISH_ES = "es-ES"
    ENGLISH_US = "en-US"
    ENGLISH_IN = "en-IN"
    ENGLISH_GB = "en-gb"
    ENGLISH_CA = "en-CA"
    ENGLISH_AU = "en-AU"
    GERMAN = "de-DE"
    DANISH = "da-DK"
    CATALAN = "ca-ES"
