# Generated by Django 2.2 on 2019-04-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_rec_message_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='deleted',
            field=models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Признак удаления'),
        ),
        migrations.AlterField(
            model_name='messages_state',
            name='deleted',
            field=models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Признак удаления'),
        ),
        migrations.AlterField(
            model_name='messages_theme',
            name='deleted',
            field=models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Признак удаления'),
        ),
    ]
