# Generated by Django 2.2.5 on 2019-09-04 17:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0050_messages_checksum'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messages',
            unique_together={('guid', 'theme', 'state', 'user', 'to_whom')},
        ),
    ]
