from tala.model.action import TOP, UP
from tala.model.individual import Yes, No

ACTION_INTENT = "action"
QUESTION_INTENT = "question"
ANSWER_INTENT = "answer"
ANSWER_NEGATION_INTENT = "answer_negation"
USER_REPORT_INTENT = "user_report"
BUILTIN_INTENTS = [Yes.YES, No.NO, TOP, UP]
VALID_INTENT_MOVES = [ACTION_INTENT, QUESTION_INTENT] + BUILTIN_INTENTS
VALID_ANSWER_MOVES = [ANSWER_INTENT, ANSWER_NEGATION_INTENT]
NEGATIVE_INTENT = "NEGATIVE"
