
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-22T14:23:53+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "0b474efbdd949091753858b3cd0eaed082439e11",
 "version": "2.0.54.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
