# Generated by Django 2.2.4 on 2019-08-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clndr', '0031_auto_20190822_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift_day',
            name='begindinnertime',
            field=models.TimeField(db_index=True, verbose_name='Начало перерыва на обед'),
        ),
        migrations.AlterField(
            model_name='shift_day',
            name='begintime',
            field=models.TimeField(db_index=True, verbose_name='Начало'),
        ),
        migrations.AlterField(
            model_name='shift_day',
            name='enddinnertime',
            field=models.TimeField(db_index=True, verbose_name='Конец перерыва на обед'),
        ),
        migrations.AlterField(
            model_name='shift_day',
            name='endtime',
            field=models.TimeField(db_index=True, verbose_name='Конец'),
        ),
    ]
