# Generated by Django 2.2.4 on 2019-08-23 15:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('clndr', '0040_auto_20190823_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift_day_relax',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата мягкого удаления')),
                ('editing', models.BooleanField(default=True, verbose_name='Возможность редактирования')),
                ('deliting', models.BooleanField(default=True, verbose_name='Возможность удаления')),
                ('lastmodified', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Последнее обновление')),
                ('begintime', models.TimeField(db_index=True, verbose_name='Начало периода')),
                ('endtime', models.TimeField(db_index=True, verbose_name='Конец периода')),
                ('shiftday', isc_common.fields.related.ForeignKeyProtect(on_delete=django.db.models.deletion.PROTECT, to='clndr.Shift_day')),
            ],
            options={
                'verbose_name': 'Запланированные перекуры и отдыхи',
            },
        ),
    ]
