# Generated by Django 2.2.4 on 2019-08-24 18:30

from django.db import migrations
import isc_common.fields.code_field


class Migration(migrations.Migration):

    dependencies = [
        ('clndr', '0048_auto_20190824_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifts',
            name='color',
            field=isc_common.fields.code_field.CodeField(blank=True, null=True),
        ),
    ]
