
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-17T08:15:03+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b96b470cf8d39c320a8ab9aa083d26c4cae5ff19",
 "version": "1.71"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
