# Generated by Django 2.2.3 on 2019-07-03 19:40

from django.db import migrations
import django.db.models.deletion
import isc_common.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('refs', '0007_type_param_values_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_param_values',
            name='type',
            field=isc_common.fields.related.ForeignKeyProtect(default=None, on_delete=django.db.models.deletion.PROTECT, to='refs.Type_param'),
        ),
    ]
