__author__ = "Jia Jia"
__author_email__ = "angersax@sina.com"
__description__ = "Metal Metrics"
__license__ = "Apache-2.0"
__title__ = "metalmetrics"
__url__ = "https://github.com/craftslab/metalmetrics"
__version__ = "7.0.2"
