
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-17T04:26:25+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0ecb8fa881db66141a21e865175b9326cfe6c530",
 "version": "1.14.6.post.dev111"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
