#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['stringliteral']

package_data = \
{'': ['*']}

extras_require = \
{'dev': ['pylint', 'nox', 'pytest-cov', 'coverage[toml]>=5.0.3', 'pre-commit'],
 'test': ['pytest', 'pytest-asyncio', 'pytest-mock']}

setup(name='stringliteral',
      version='0.0.1',
      description='stringliteral',
      author='Sander Teunissen',
      author_email=None,
      url=None,
      packages=packages,
      package_data=package_data,
      extras_require=extras_require,
      python_requires='>=3.7',
     )
