
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-19T04:26:09+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "81df93b4bf5be9ef553bc2d35c84f1b2c343df35",
 "version": "1.15.0.post.dev4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
