
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-16T10:31:54+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "46cd9dfcf36efd37475170d99b04ae0c79f3f93d",
 "version": "v1.11.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
