# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\steven.king\git\pipeline\lib\python\ts_publisher\src\publisher\gui\\resources\channel_editor.ui'
#
# Created: Mon Feb 24 15:17:41 2020
#      by: pyside2-uic  running on PySide2 5.6.0a1.dev1528216830
#
# WARNING! All changes made in this file will be lost!

from Qt import QtCompat, QtCore, QtGui, QtWidgets

class Ui_channel_editor(object):
    def setupUi(self, channel_editor):
        channel_editor.setObjectName("channel_editor")
        channel_editor.resize(536, 425)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(channel_editor)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.header = QtWidgets.QFrame(channel_editor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header.sizePolicy().hasHeightForWidth())
        self.header.setSizePolicy(sizePolicy)
        self.header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header.setObjectName("header")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.header)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = TSTitle(self.header)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.line = QtWidgets.QFrame(self.header)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.verticalLayout_2.addWidget(self.header)
        self.channel_tbl = QtWidgets.QTableView(channel_editor)
        self.channel_tbl.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.channel_tbl.setAlternatingRowColors(True)
        self.channel_tbl.setSortingEnabled(True)
        self.channel_tbl.setObjectName("channel_tbl")
        self.channel_tbl.horizontalHeader().setStretchLastSection(False)
        self.channel_tbl.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.channel_tbl)
        self.display_images = QtWidgets.QCheckBox(channel_editor)
        self.display_images.setObjectName("display_images")
        self.verticalLayout_2.addWidget(self.display_images)
        self.badge_banner_widget = QtWidgets.QWidget(channel_editor)
        self.badge_banner_widget.setObjectName("badge_banner_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.badge_banner_widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.badge = CustomGraphicsView(self.badge_banner_widget)
        self.badge.setObjectName("badge")
        self.gridLayout.addWidget(self.badge, 1, 0, 1, 1)
        self.banner = CustomGraphicsView(self.badge_banner_widget)
        self.banner.setObjectName("banner")
        self.gridLayout.addWidget(self.banner, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.badge_banner_widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.badge_banner_widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.badge_banner_widget)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(channel_editor)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.msg = QtWidgets.QPlainTextEdit(channel_editor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.msg.sizePolicy().hasHeightForWidth())
        self.msg.setSizePolicy(sizePolicy)
        self.msg.setMaximumSize(QtCore.QSize(16777215, 50))
        self.msg.setObjectName("msg")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.msg)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.submit_btn = QtWidgets.QPushButton(channel_editor)
        self.submit_btn.setObjectName("submit_btn")
        self.verticalLayout_2.addWidget(self.submit_btn)
        self.add_row = QtWidgets.QAction(channel_editor)
        self.add_row.setObjectName("add_row")
        self.delete_row = QtWidgets.QAction(channel_editor)
        self.delete_row.setObjectName("delete_row")

        self.retranslateUi(channel_editor)
        QtCore.QMetaObject.connectSlotsByName(channel_editor)
        channel_editor.setTabOrder(self.channel_tbl, self.msg)
        channel_editor.setTabOrder(self.msg, self.submit_btn)

    def retranslateUi(self, channel_editor):
        channel_editor.setWindowTitle(QtCompat.translate("channel_editor", "Channel Editor", None, -1))
        self.label.setText(QtCompat.translate("channel_editor", "Channel Editor", None, -1))
        self.display_images.setText(QtCompat.translate("channel_editor", "Display Images", None, -1))
        self.label_3.setText(QtCompat.translate("channel_editor", "Badge", None, -1))
        self.label_4.setText(QtCompat.translate("channel_editor", "Banner", None, -1))
        self.label_2.setText(QtCompat.translate("channel_editor", "Comment", None, -1))
        self.submit_btn.setText(QtCompat.translate("channel_editor", "Save Changes", None, -1))
        self.add_row.setText(QtCompat.translate("channel_editor", "Add Row", None, -1))
        self.delete_row.setText(QtCompat.translate("channel_editor", "Delete Row", None, -1))

from publisher.gui.widgets import TSTitle, CustomGraphicsView
