
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-16T12:24:27+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "da2edac8c2eb7e6bfcae4eb726c79bd9b7f51be3",
 "version": "0.26.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
