
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-21T09:11:36+0330",
 "dirty": false,
 "error": null,
 "full-revisionid": "88e1ee479b26acb4755b8c34a9ba4fb7bee12446",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
