# Generated by Django 2.2 on 2019-04-14 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isc_common', '0015_auto_20190414_0756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='deleted',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='user_permission',
            old_name='deleted',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='usergroup',
            old_name='deleted',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='usergroup_permission',
            old_name='deleted',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='widgets_trees',
            old_name='deleted',
            new_name='deleted_at',
        ),
    ]
