# Generated by Django 3.0.7 on 2020-06-25 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isc_common', '0052_mat_view'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mat_view',
        ),
    ]
