# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import DataService_pb2 as DataService__pb2


class DataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadData = channel.stream_unary(
                '/xgt.DataService/UploadData',
                request_serializer=DataService__pb2.UploadDataRequest.SerializeToString,
                response_deserializer=DataService__pb2.UploadDataResponse.FromString,
                )
        self.DownloadData = channel.unary_stream(
                '/xgt.DataService/DownloadData',
                request_serializer=DataService__pb2.DownloadDataRequest.SerializeToString,
                response_deserializer=DataService__pb2.DownloadDataResponse.FromString,
                )
        self.IngestUri = channel.unary_unary(
                '/xgt.DataService/IngestUri',
                request_serializer=DataService__pb2.IngestUriRequest.SerializeToString,
                response_deserializer=DataService__pb2.IngestUriResponse.FromString,
                )
        self.EgestUri = channel.unary_unary(
                '/xgt.DataService/EgestUri',
                request_serializer=DataService__pb2.EgestUriRequest.SerializeToString,
                response_deserializer=DataService__pb2.EgestUriResponse.FromString,
                )


class DataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadData(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestUri(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EgestUri(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadData': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadData,
                    request_deserializer=DataService__pb2.UploadDataRequest.FromString,
                    response_serializer=DataService__pb2.UploadDataResponse.SerializeToString,
            ),
            'DownloadData': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadData,
                    request_deserializer=DataService__pb2.DownloadDataRequest.FromString,
                    response_serializer=DataService__pb2.DownloadDataResponse.SerializeToString,
            ),
            'IngestUri': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestUri,
                    request_deserializer=DataService__pb2.IngestUriRequest.FromString,
                    response_serializer=DataService__pb2.IngestUriResponse.SerializeToString,
            ),
            'EgestUri': grpc.unary_unary_rpc_method_handler(
                    servicer.EgestUri,
                    request_deserializer=DataService__pb2.EgestUriRequest.FromString,
                    response_serializer=DataService__pb2.EgestUriResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xgt.DataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/xgt.DataService/UploadData',
            DataService__pb2.UploadDataRequest.SerializeToString,
            DataService__pb2.UploadDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DownloadData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/xgt.DataService/DownloadData',
            DataService__pb2.DownloadDataRequest.SerializeToString,
            DataService__pb2.DownloadDataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IngestUri(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xgt.DataService/IngestUri',
            DataService__pb2.IngestUriRequest.SerializeToString,
            DataService__pb2.IngestUriResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EgestUri(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/xgt.DataService/EgestUri',
            DataService__pb2.EgestUriRequest.SerializeToString,
            DataService__pb2.EgestUriResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
