# Generated by Django 3.0 on 2020-04-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appel_crises', '0005_auto_20200421_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='verified_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
