# Generated by Django 3.0.5 on 2020-04-26 11:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('appel_crises', '0006_auto_20200424_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOffset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('offset', models.IntegerField(db_index=True, default=0)),
            ],
        ),
    ]
