# Generated by Django 3.0.5 on 2020-05-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appel_crises', '0016_auto_20200504_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='news',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
