
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-02-17T11:19:56+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "22a0629714995f8ea7852f48621ce0627f6a8b2c",
 "version": "0.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
