# Generated by Django 2.2.7 on 2019-11-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0008_auto_20191116_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='ip_address',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='history',
            name='user_agent',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
