# Generated by Django 2.2.7 on 2019-11-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0010_auto_20191116_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='user_agent',
            field=models.TextField(),
        ),
    ]
